language: python
# Which python versions to use
python:
  - 2.7
  - 3.5
  - 3.6
# Commands to set up the environment
install:
  - pip install -r requirements.txt
  - pip install -e .
# Command to run tests
script:
  - pytest